on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.38'
          - '5.20' # Earliest supported by current Catalyst::Runtime

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: perl -V
      - run: cpanm --notest --installdeps --verbose .
      - run: perl Makefile.PL
      - run: make
      - run: prove -wlvmb t
